name: Build .NET Framework Project

on:
  push:
  pull_request:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore DingoConfigurator\DingoConfigurator.sln

    - name: Build solution
      run: msbuild DingoConfigurator\DingoConfigurator.sln -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DingoConfigurator
        path: DingoConfigurator\DingoConfigurator\bin\Release\